---
- hosts: all
  gather_facts: False
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
   - name: install python 2
     raw: test -e /usr/bin/python || (yum -y update && yum install -y python-minimal)
 
  roles:
     - server
     - php
     - mysql
     - wordpress
